added logging
ConnieML/Connie-RTC pull request #52
Opened 2023-07-20 01:04 UTC by nikki2906

2023-08-07 06:12 UTC, ZzRanger requested changes
Looking good! After connecting it to the endpoint I got it to work! Feel free to use this phone number for now: `+17198266643`

Feel free to reach out to me if you need any help. This is our last week of development, so don't hesitate to ask for help so we can get this done by the end of this week :)

2023-08-07 06:12 UTC, ZzRanger commented on .env.example
> +TWILIO_AUTH_TOKEN=5c9c29a62cd72a77feb1ccb4d5a5fe44
Remove these values so we don't leak our Twilio account sid or auth token

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/index.tsx
Is there a reason why we deleted this file?

2023-08-07 06:12 UTC, ZzRanger commented on package-lock.json
We can remove this file

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +        const response = await fetch('/api/endpoint-url');
Should we make an API request to `/api/calls` here?

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +        const response = await fetch('/api/endpoint-url');
Looking at the code in `calls.ts`, it seems like it reads the phone number, start time, and end time from passing in query parameters. Here's an example of how to use query parameters: `localhost:3000/api/calls?phoneNumber=+17198266643&startTime=2023-06-10`

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +  const transformData = (data: any[]) => {
Should probably not use `any` types but we'll address this after everything else.

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/api/calls.ts
> +      from: phoneNumber,
From the [docs](https://twilio.com/docs/libraries/reference/twilio-node/4.13.0/interfaces/rest_api_v2010_account_call.CallListInstanceOptions.html), it seems like the `from` property only covers calls that are initiated by said phone number, and not calls that the phone number receives. Similarly, the `to` property only covers calls received by a phone number. How can we write the code so that we get all phone calls made to and from the phone number?

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
Looking at the screenshot it seems like we can only see phone call logs for 1 day. Can we edit this so that we can see phone calls logs for other time intervals like a week and a month as well?

<img width="1440" alt="Screenshot 2023-07-24 at 7 33 25 PM" src="https://github.com/ConnieML/Connie-RTC/assets/47403443/ae01cb29-0036-4ecb-adff-a4f690a7aa6d">

2023-08-07 06:12 UTC, ZzRanger commented on package-lock.json
Delete

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +        const response = await fetch('/api/endpoint-url');
Seems like we're not fetching the data here. Can we change the url to call the correct endpoint?

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +        const response = await fetch('/api/endpoint-url');
You will need to pass in the start time and end time as query parameters

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +      yAxesMax = 2500; // Maximum value on y-axes for 'day' filter
Currently the yAxesMax values are set arbitrarily. Maybe we can set them dynamically, like 1.25 * (max value in transformedData)?

2023-08-07 06:12 UTC, ZzRanger commented on src/pages/logging.tsx
> +        <canvas ref={callChartDataRef} className="w-[27vw]" />
Can we make both graphs fit on the screen?

2023-08-08 22:44 UTC, nikki2906 commented on src/pages/index.tsx
Oh, it kept giving me errors so I deleted it. But I will add it back

2023-08-14 03:08 UTC, ZzRanger approved these changes
Good enough for now. Next cohort can update lolol

2023-08-14 03:08 UTC, ZzRanger commented on package.json
Uhhh we kinda need this to install dependencies 😅

2023-08-14 03:17 UTC, ZzRanger approved these changes
LGTM!

2023-08-14 03:19 UTC, merged